wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.12
    start_time: 1670954815.265074
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 1
      - 7
      - 23
      - 38
      4: 3.9.12
      5: 0.13.6
      8:
      - 1
      - 4
      - 5
